config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # get 'dashboard', to: 'pages#dashboard'

  resources :records
  resources :profiles, only: [:update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'profiles/edit', to: 'profiles#edit'
  get 'profile', to: 'profiles#show'
  get '/records/:id/visitor', to: 'records#visitor'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/record.rb
class Record < ApplicationRecord
  before_create :generate_token
  belongs_to :user
  has_many :record_symptoms, dependent: :destroy
  has_many :symptoms, through: :record_symptoms
  has_one_attached :photo
  has_one_attached :pdf

  private

  def generate_token
    self.token = rand(0..1000).to_s
  end

end

app/models/record_symptom.rb
class RecordSymptom < ApplicationRecord
  belongs_to :record
  belongs_to :symptom
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  has_many :record_symtoms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :records
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
  before_create :add_profile

  private

  def add_profile
    @profile = Profile.new
    self.profile = @profile
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_up_path_for(resource)
    profiles_edit_path(resource)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    # @profile = current_user.profile
    @profile = Profile.find(current_user.profile.id)

  end


  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    @profile.update!(profile_params)
    redirect_to '/profile'
  end

  private

  def profile_params
    params.require(:profile).permit(:date_of_birth, :gender, :allergies, :medication, :dosage, :times_per_day, :vaccinations, :blood_type, :race, :user_id  )
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  skip_before_action :authenticate_user!, only: :visitor

  def index
    @records = Record.all
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    @record.user = current_user

    @symptoms = params[:record][:symptom][:symptoms][1..]

    @symptoms.each do |item|
      @record_symptom = RecordSymptom.new
      symptom = Symptom.find(item)
      @record_symptom.symptom = symptom
      @record_symptom.record = @record
      @record_symptom.save
    end

    if @record.save
      redirect_to records_path
    else
      render :new
    end
  end

  def show
    @record = Record.find(params[:id])
    @record.user = current_user
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    @record.update(record_params)
    redirect_to record_path(@record)
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to records_path, status: :see_other
  end

  def visitor
    @record = Record.find(params[:id])
    if params[:token] != @record.token
    redirect_to root_path
    else
    render :show
    end
  end


  private

  def record_params
    params.require(:record).permit(:disease, :notes, :medication, :date, :user_id, :photo, :pdf)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Udo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  </div>
    <%= yield %>
    <% if !current_page?(root_path) %>
      <lottie-player src="https://assets5.lottiefiles.com/packages/lf20_gduz3izv.json" class="animated-background" background="transparent"  speed="2"  style="position:absolute"  loop  autoplay></lottie-player>
      <%= render 'shared/navbar' %>
    <% end %>
      <%= render 'shared/flashes' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <script src="https://kit.fontawesome.com/161b8f37c0.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>dashboard</h1>
<p><%= link_to "profile", '/profile' %></p>
<p><%= link_to "records (new)", new_record_path %></p>
<p><%= link_to "see all records (index)", records_path %></p>

app/views/pages/home.html.erb
<div class="video-container">

  <%= video_tag 'udo_health_komp.mp4', autoplay: :autoplay, loop: :loop, muted: :muted, class: "video_tag" %>


  <div class="text-landing">
    <h1 class="home-h">Udo</h1>
    <br>
      <br>
        <p class="home-p">Transforming data into actionable solutions</p>
        <br>
          <br>
            <% if !user_signed_in? %>
              <div class="d-flex d-flex-ghost">
                <%= link_to "Login", new_user_session_path, class: "btn btn-ghost" %>
                <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-ghost" %>
              </div>
              <% else %>
                <%= link_to "All records", records_path, class: "btn btn-ghost" %>
            <% end %>
            <div class="arrow-down">
            <lottie-player src="https://assets6.lottiefiles.com/packages/lf20_kxjicwsk.json"   background="transparent"  speed="1"  style="width: 50px; height: 50px;"  loop  autoplay></lottie-player>

            </div>
          </div>
        </div>


        <%# <section id="subscribe-form" class="subscribe-form wf-section"></section> %>
        <section id="feature-section" class="feature-section wf-section">
          <div class="flex-container w-container">
            <div class="feature-image-mask">
              <%= image_tag "team-picture.jpg", class: "w-100 pic" %>
            </div>
            <div>
              <h2>We are Udo</h2>
              <p>We are an innovative global company, driven by one purpose: we build effective communication between healthcare professionals and patients.</p>
            </div>
          </div>
        </section>


        <div class="container-fluid pad">
          <h2>Get in touch</h2>
          <p>If you have any concerns about keeping accurate records, get in touch with us to see how we can support you</p>
          <div class="w-form space-at-buttm">
            <form id="email-form" name="email-form" data-name="Email Form" method="get" class="subscribe-form-flex">
              <div class="subscribe-form-input-wrapper">
                <label for="Subscriber-Email" id="subscribe-email">Email</label>
                <input type="email" class="subscribe-form-input w-input" maxlength="256" name="Subscriber-Email" data-name="Subscriber Email" placeholder="" id="Subscriber-Email" required=""></div>
                <input type="submit" value="Submit" data-wait="Please wait..." class="w-button btn-color"></form>
                <%# <div class="w-form-done">
                          <div>Thank you! Your submission has been received!</div>
                        </div>
                        <div class="w-form-fail">
                          <div>Oops! Something went wrong while submitting the form.</div>
                        </div> %>
              </div>
            </div>

app/views/profiles/edit.html.erb
<div class="header">
  <%= link_to :back do%>
  <i class="fa fa-angle-left" style="color:black; padding:10px"></i>
<% end %>
<h1 class="text-center">Edit profile</h1>
</div>

<div class="container new_form">

<%= simple_form_for(@profile) do |f| %>
  <%= f.input :gender%>
  <%= f.input :date_of_birth, as: :date, html5: true%>
  <%= f.input :allergies %>
  <%= f.input :medication %>
  <%= f.input :dosage, :label => "Dosage (ml)" %>
  <%= f.input :times_per_day %>
  <%= f.input :vaccinations %>
  <%= f.input :blood_type %>
  <%= f.input :race %>
  <%= f.button :submit, "Submit" ,class:"btn btn-dark" %>
<% end %>
</div>

app/views/profiles/new.html.erb
<div class="container new_form">
<h1>New Profile</h1>

<%= simple_form_for(@profile) do |f| %>
  <%= f.input :date_of_birth%>
  <%= f.input :allergies %>
  <%= f.input :medication %>
  <%= f.input :dosage %>
  <%= f.input :times_per_day %>
  <%= f.input :vaccinations %>
  <%= f.input :blood_type %>
  <%= f.input :race %>
  <%= f.button :submit, "Edit" ,class:"btn btn-dark" %>
<% end %>
</div>

app/views/profiles/show.html.erb
<div>
  <div class="animation-container" id="animation-container">
    <div class="edit-btn">
      <%= link_to profiles_edit_path, class: "btn " do%>
      <i class="fa fa-pen" aria-hidden="true"></i>
    <% end %>
    <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "btn" do %>
      <i class="fa-solid fa-arrow-right-from-bracket"></i>
    <% end %>
  </div>
  <h1 class="text-center mb-4">
    Profile</h1>
  <lottie-player src="https://assets2.lottiefiles.com/packages/lf20_zfszhesy.json" background="transparent" speed="0.5" style="width: 150px; height: 150px; margin: 0 auto;" loop autoplay></lottie-player>
</div></div>
<div class="profile-show-container">
  <p class="profile-show-text">
    <i class="icon fa-solid fa-mars-and-venus"></i>
    <strong>Gender of birth</strong>:
    <%= @profile.gender %></p>
  <p class="profile-show-text">
    <i class="icon fa-solid fa-cake-candles"></i>
    <strong>Date of birth</strong>:
      <%= @profile.date_of_birth %></p>
  <p class="profile-show-text">
    <i class="icon fa-solid fa-person-dots-from-line"></i>
    <strong>Allergies</strong>:
    <%= @profile.allergies %></p>
  <p class="profile-show-text">
    <i class="icon fa-solid fa-tablets"></i>
    <strong>Medication:</strong>
    <%= @profile.medication %>
  </p>
  <p class="profile-show-text">
    <i class="icon fa-solid fa-pills"></i>
    <strong>Dosage</strong>:
    <%= @profile.dosage %> ml</p>
  <p class="profile-show-text">
    <i class="icon fa-solid fa-clock-rotate-left"></i>
    <strong>Times per day</strong>:
    <%= @profile.times_per_day %></p>
  <p class="profile-show-text">
    <i class="icon fa-solid icon fa-syringe"></i>
    <strong>Vaccinations</strong>:
    <%= @profile.vaccinations %></p>
  <p class="profile-show-text">
    <i class="icon fa-solid fa-droplet"></i>
    <strong>Blood type</strong>:
    <%= @profile.blood_type %></p>
  <p class="profile-show-text">
    <i class="icon fa fa-user-group"></i>
    <strong>Race</strong>:
    <%= @profile.race %></p>
  <div class="nav-item logout-btn"></div>

</div>

app/views/records/edit.html.erb
<div class="container">
<div class="header">
  <%= link_to :back do%>
  <i class="fa fa-angle-left" style="color:black; padding:10px"></i>
<% end %>
<h1 class="text-center">Edit a record</h1>
</div>

<%= simple_form_for(@record) do |f| %>
  <%= f.input :disease%>
  <%= f.input :notes %>
  <%= f.input :medication %>
  <%= f.input :date, :label => "Doctors visit date" %>
  <%= f.input :photo, as: :file, label: "Upload image"%>
  <%= f.simple_fields_for :symptom do |p| %>
    <%= p.input :symptoms, :as => :select, :collection => Symptom.all, input_html: { multiple: true }, prompt: 'Select symptom'  %>
  <% end %>

  <div class="d-flex justify-content-center m-4">
    <%= f.button :submit, "Submit" ,class:"btn btn-dark" %>
  </div>
<% end %>
</div>

app/views/records/index.html.erb
<div class="background">

<%# <lottie-player src="https://assets1.lottiefiles.com/packages/lf20_w6y7r1ap.json"  background="transparent"  speed="2"  style="position:absolute"  loop  autoplay></lottie-player> %>

<br>
  <h1 class="text-center ">All records</h1>
  <div class="icon">
    <lottie-player src="https://assets6.lottiefiles.com/packages/lf20_QJbPLt.json"  background="transparent"  speed="1"  style="width: 150px; height: 150px; margin: 0 auto;"  loop  autoplay></lottie-player>
  </div>
  <div class="all-records">
    <% @records.each do |item| %>
      <div class="card">
        <div class="card-body card-edits">
          <%= link_to record_path(item) do %>
            <div class="record-disease"><%= item.disease %></div>
            <div class="record-date"><%= item.date.strftime("%B %d, %Y %a") %></div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/records/new.html.erb
<h1 class="text-center m-4">Create a record</h1>
<div class="container" data-controller="create_form">

<%= simple_form_for(@record) do |f| %>
  <%= f.input :disease, :label => "Sickness"%>
  <%= f.input :notes %>
  <%= f.input :medication %>
  <%= f.input :date, :label => "Doctors visit date", html5: true  %>
  <%= f.input :photo, as: :file, label: "Upload image"%>
  <%= f.input :pdf, as: :file, label: "Upload document:" %>
  <%= f.simple_fields_for :symptom do |p| %>
    <%= p.input :symptoms, :as => :select, :collection => Symptom.all, input_html: { multiple: true }, prompt: 'Select symptom'  %>
  <% end %>

  <div class="d-flex justify-content-center mb-4">
    <%= f.button :submit, "Submit" ,class:"btn btn-dark" %>
  </div>
<% end %>
</div>

app/views/records/show.html.erb
<% if current_user %>
    <div class="btns">
        <%= link_to :back do%>
          <i class="fa fa-angle-left" style="color:black; padding:10px"></i>
        <% end %>
        <div>
            <%= mail_to "marioleonel26@gmail.com", subject: "Requested record", body: "The content of this message is confidential. If you have received it by mistake, please inform us by an email reply and then delete the message. It is forbidden to copy, forward, or in any way reveal the contents of this message to anyone. The integrity and security of this email cannot be guaranteed over the Internet. Please click on the link to see the record: \n\n #{request.original_url}/visitor?token=#{@record.token} \n\n -Your Udo team",  class: "btn" do %>
              <i class="fa fa-share-nodes"></i>
            <% end %>
            <%= link_to edit_record_path(@record), class: "btn " do%>
            <i class="fa fa-pen" aria-hidden="true"></i>
          <% end %>
          <%= link_to record_path(@record),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class: "btn" do%>
            <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
        </div>
    </div>
<div>
<% end %>

  <h1 class="text-center mb4">Record</h1>
    <lottie-player src="https://assets6.lottiefiles.com/temp/lf20_YMAG36.json"  background="transparent"  speed="1"  style="width: 150px; height: 150px; margin: 0 auto;"  loop  autoplay></lottie-player>
<div class="wrapper">
  <div class="record-card" style="width: 100%;">
    <div class="card-body card-body-mod">
      <div class="card-box">
        <h5 class="card-title record-title">Sickness</h5>
        <div><%= @record.disease %></div>
      </div>

      <div class="card-box">
        <h5 class="card-title record-title">Date</h5>
        <div><%= @record.date.strftime("%B %d, %Y %a") %></div>
      </div>

      <div class="card-box">
        <h5 class="card-title record-title">Symptoms</h5>

        <% if @record.symptoms %>
            <% @record.symptoms.each do |item| %>
              <div class="symptoms"><%= item.name %></div>
            <% end %>
          <% else %>
            <p>no symptoms yet..</p>
        <% end %>

      </div>

      <div class="card-box">
        <h5 class="card-title record-title">Medication</h5>
        <div><%= @record.medication %></div>
      </div>

      <div class="card-box">
        <h5 class="card-title record-title">Notes</h5>
        <div><%= @record.notes %></div>
      </div>

      <div class="card-box">
        <h5 class="card-title record-title">Image</h5>

        <% if @record.photo.attached? %>
        <%= link_to @record.photo.url do %>
          <%= cl_image_tag @record.photo.key, height: 200, width: 200, crop: :fill %>
        <%end%>
          <% else %>
          <p>No image yet..</p>
        <% end %>

        <% if @record.pdf.attached? %>
          <div><%=  link_to "pdf file", @record.pdf %></div>
          <% else %>
          <p>No files yet..</p>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-lewagon">
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>

        <% if user_signed_in? %>
          <div class="nav-item mx-2">
            <%= link_to image_tag("add_record.svg"), new_record_path, class: "nav-link" %>
          </div>
          <div class="nav-item active mx-2">
            <%= link_to image_tag("allrecords.svg"), records_path, class: "nav-link" %>
          </div>
          <div class="nav-item mx-2">
            <%= link_to image_tag("profile.svg"), "/profile", class: "nav-link" %>
          </div>
        <% else %>
          <div class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </div>
        <% end %>
</div>